name: SPARQL Unicorn Ontology Documentation CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with:
      version: v018
      rdffilepath: rdf/ci.ttl rdf/drillcores.ttl rdf/holywells.ttl rdf/ogham.ttl
      docpath: docs
      prefixns: http://research-squirrel-engineers.github.io/osm2lod/
      prefixnsshort: osm2lod
      indexpages: true
      createcollections: true
      createVOWL: true
      preferredlang: en
      ghpages: true
      metadatatable: true
      createnonNSPages: true
      logourl: https://raw.githubusercontent.com/Research-Squirrel-Engineers/osm2lod/main/osm2lod_logo.png
      templatedir: https://github.com/Research-Squirrel-Engineers/unicorn-ontdoc-template-squirrels/archive/refs/tags/scrat.1.zip
      ogcapifeatures: false
      datasettitle: osm2lod
